### ISSUE TITLE
проверка на отсутствие

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_19#1]
https://github.com/xydoy92/lesson_19/blob/5e46d2dcce42d0bd825706e5e31c188d55b1e1ab/script.js#L53

в случае если у тебя здесь будет undefined или null, твоя валидация не сработает. Используй лучше логический оператор "!" в таких случаях.

**Comment by xydoy92** [comment]
Вот тут не понял. В каких случаях у меня может быть undefined or null? Логический оператор "!" — это "!==" или что? Тоже не понял. Т.е. не ясно, как может возникнуть ошибка и как её исправить.

**Comment by xydoy92** [comment]
Done!
