### ISSUE TITLE
Заменить на find

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_19#2]
https://github.com/xydoy92/lesson_19/blob/5e46d2dcce42d0bd825706e5e31c188d55b1e1ab/script.js#L69

Я бы заменил этот перебор на метод find, написал бы функцию, которая возвращает к примеру true или false или даже целый объект если надо,  и потом бы уже выполнял нужные действия

**Comment by xydoy92** [comment]
Спасибо, так намного лучше.
Done!
