### ISSUE TITLE
Заведи константу

### ISSUE THREAD

**Issue by casa7x** [xydoy92/lesson_19#4]
https://github.com/xydoy92/lesson_19/blob/5e46d2dcce42d0bd825706e5e31c188d55b1e1ab/script.js#L23

Раз ты уже много где используешь 'nodisplay', то будет неплохо если ты заведешь константу для него и будешь ее просто передавать где нужно, а не хардкодить везде, плюс если твой класс изменится к примеру, тебе надо будет только значение в одном месте поменять, а не везде искать

**Comment by xydoy92** [comment]
Done!
